# Generated by Django 4.1 on 2022-08-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordluv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='examples',
            field=models.TextField(null=True),
        ),
    ]
