# Generated by Django 4.1 on 2022-09-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordluv_app', '0002_word_examples'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='slug',
            field=models.SlugField(default='default'),
            preserve_default=False,
        ),
    ]
