# Generated by Django 4.1 on 2022-09-14 10:38

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordluv_app', '0006_alter_word_lastshown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='word'),
        ),
    ]
